#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate --skip-checks
python manage.py insert_default_data --skip-checks
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
