# Generated by Django 4.2.8 on 2025-11-19 16:16

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    EntityType = apps.get_model("core", "EntityType")
    for entity in EntityType.objects.all():
        entity.id = uuid.uuid4()
        entity.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_availablemodule_serverstatus_workerstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitytype",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="entitytype",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, null=False, unique=True),
        ),
    ]
