# Generated by Django 4.2.8 on 2025-11-19 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_entitytype_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitytype",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
