# Generated by Django 4.2.8 on 2025-11-19 14:57

from django.db import migrations, models
import uuid

from threatr.core.models import Entity, EntityType, Event, Request


def apply_new_pk(apps, schema_editor):
    for e in Entity.objects.all():
        e.type = EntityType.objects.get(short_name=e.type.short_name)
        e.save()
    for e in Event.objects.all():
        e.type = EntityType.objects.get(short_name=e.type.short_name)
        e.save()
    for e in Request.objects.all():
        e.type = EntityType.objects.get(short_name=e.type.short_name)
        e.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_entitytype_id"),
    ]

    operations = [
        migrations.RunPython(apply_new_pk, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="entitytype",
            name="short_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
