# Generated by Django 4.0.10 on 2023-03-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityrelation',
            name='obj_from_id',
        ),
        migrations.RemoveField(
            model_name='entityrelation',
            name='obj_from_type',
        ),
        migrations.RemoveField(
            model_name='entityrelation',
            name='obj_to_id',
        ),
        migrations.RemoveField(
            model_name='entityrelation',
            name='obj_to_type',
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='obj_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source_of_relation', to='core.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='obj_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target_of_relation', to='core.entity'),
            preserve_default=False,
        ),
    ]
