# Generated by Django 4.0.10 on 2023-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_entityrelation_obj_from_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='request',
        ),
    ]
