# Generated by Django 4.0.10 on 2023-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_entity_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='Give a meaningful name to this entity.', max_length=512, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name', 'super_type', 'type')},
        ),
    ]
