# Generated by Django 4.0.10 on 2023-03-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='involved_entity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
            preserve_default=False,
        ),
    ]
