# Generated by Django 4.0.10 on 2023-03-12 10:19

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_involved_entity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('type', 'name', 'first_seen', 'last_seen', 'involved_entity')},
        ),
        migrations.AlterField(
            model_name='entity',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='entityrelation',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
