# Generated by Django 4.0.10 on 2023-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_unique_together_alter_entity_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Add more details about this object.', null=True),
        ),
    ]
