# Generated by Django 4.0.10 on 2023-03-13 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_event_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcredentials',
            name='last_usage',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
