# Generated by Django 4.0.10 on 2023-03-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vendorcredentials_last_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytype',
            options={'ordering': ['name'], 'verbose_name': 'Entity type', 'verbose_name_plural': 'Entity types'},
        ),
        migrations.AlterModelOptions(
            name='vendorcredentials',
            options={'ordering': ['last_usage']},
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Latest modification of this object.'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='super_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='core.entitysupertype'),
        ),
    ]
