# Generated by Django 4.2.8 on 2025-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_entity_options_alter_event_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableModule",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("vendor", models.CharField(max_length=256)),
                ("configured", models.IntegerField(default=0)),
                ("description", models.TextField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ServerStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("git_commit_hash", models.CharField(max_length=256)),
                ("cached_entities", models.IntegerField(default=0)),
                ("cached_events", models.IntegerField(default=0)),
                ("cached_relations", models.IntegerField(default=0)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WorkerStatus",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=64)),
                ("uptime", models.FloatField(default=0.0)),
                ("enqueued_tasks", models.IntegerField(default=0)),
                ("available_results", models.IntegerField(default=0)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
