# Generated by Django 4.2.8 on 2025-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_entitytype_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="request",
            name="type",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(max_length=32),
        ),
    ]
