# Generated by Django 4.2.8 on 2025-11-21 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_entity_type_alter_request_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={
                "ordering": ["type_old", "name"],
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="type",
            new_name="type_old",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="type",
            new_name="type_old",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="type",
            new_name="type_old",
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("name", "super_type", "type_old")},
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={
                ("type_old", "name", "first_seen", "last_seen", "involved_entity")
            },
        ),
    ]
