# Generated by Django 4.2.8 on 2025-11-21 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_entity_options_rename_type_entity_type_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitytype",
            name="short_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
