# Generated by Django 4.2.8 on 2025-11-21 12:04

from django.db import migrations, models
import django.db.models.deletion


def link_entities(apps, model):
    EntityType = apps.get_model("core", "EntityType")
    for entity in model.objects.all():
        entity.type = EntityType.objects.get(short_name=entity.type_old, super_type=entity.super_type)
        entity.save()


def link_types(apps, schema_editor):
    Entity = apps.get_model("core", "Entity")
    Event = apps.get_model("core", "Event")
    Request = apps.get_model("core", "Request")
    link_entities(apps, Entity)
    link_entities(apps, Event)
    link_entities(apps, Request)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_entitytype_id_alter_entitytype_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_of",
                related_query_name="q_type_of",
                to="core.entitytype",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of this event.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.entitytype",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_type",
                to="core.entitytype",
            ),
        ),
        migrations.RunPython(link_types, migrations.RunPython.noop),
    ]
