# Generated by Django 4.2.8 on 2025-11-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_entity_type_event_type_request_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={
                "ordering": ["type", "name"],
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="request",
            name="type_old",
        ),
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_of",
                related_query_name="q_type_of",
                to="core.entitytype",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                help_text="Type of this event.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.entitytype",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_type",
                to="core.entitytype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("name", "super_type", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={
                ("type", "name", "first_seen", "last_seen", "involved_entity")
            },
        ),
        migrations.RemoveField(
            model_name="entity",
            name="type_old",
        ),
        migrations.RemoveField(
            model_name="event",
            name="type_old",
        ),
    ]
